name: navigation-mf-CI
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CONTAINER_TAG: navigation-mf
  FILE_NAME: navigation-mf.cid

jobs:
  build:
    name: build
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3

      - name: reading running container id
        id: container-id
        run: |
          FILE="/home/`whoami`/docker-containers-id/$FILE_NAME"
          if [ -f "$FILE" ]; then
            ID=`cat $FILE`
            echo "id=$ID" >> $GITHUB_OUTPUT
          fi

      - name: stopping container, deleting file
        run: |
          FILE="/home/`whoami`/docker-containers-id/$FILE_NAME"
          if [ ! -z "${{steps.container-id.outputs.id}}" ]; then
            rm $FILE
            docker stop ${{steps.container-id.outputs.id}}
          fi

      - name: remove previous docker image
        run: docker rmi -f $CONTAINER_TAG

      - name: build docker image
        run: docker build . -t $CONTAINER_TAG

      - name: run docker container and save id
        run: |
          FILE="/home/`whoami`/docker-containers-id/$FILE_NAME"
          docker run --cidfile $FILE -d -p 8500:8500 $CONTAINER_TAG
