# name: navigation-mf-update-externals
# on:
#   push:
#     branches: ["dev"]
#   pull_request:
#     branches: ["dev"]

# jobs:
#   build:
#     name: Test
#     runs-on: [self-hosted, linux, X64]
#     steps:
#       - name: getting microfrontend name
#         id: mf-name
#         run: python3 .github/scripts/mf-name.py

#       - name: debug step
#         run: echo ${{steps.mf-name.outputs.mf-name}}

#       - name: sending request to EDS (external libraries server)
#         run: python3 .github/scripts/ext-libraries.py ${{steps.mf-name.outputs.mf-name}}
